// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMDB.Data;

namespace MyMDB.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220305120858_switchCastCRewForProdRoleOnMovieAndEpisodes")]
    partial class switchCastCRewForProdRoleOnMovieAndEpisodes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AwardRecipientMediaFile", b =>
                {
                    b.Property<int>("AwardRecipientsId")
                        .HasColumnType("int");

                    b.Property<int>("MediaFilesId")
                        .HasColumnType("int");

                    b.HasKey("AwardRecipientsId", "MediaFilesId");

                    b.HasIndex("MediaFilesId");

                    b.ToTable("AwardRecipientMediaFile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MyMDB.Models.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("MyMDB.Models.AwardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AwardCategories");
                });

            modelBuilder.Entity("MyMDB.Models.AwardRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AwardCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("AwardId")
                        .HasColumnType("int");

                    b.Property<int?>("AwardRecipientId")
                        .HasColumnType("int");

                    b.Property<int?>("CastCrewMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<int?>("JobRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieSeriesId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieStudioId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductionRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("int");

                    b.Property<int?>("RatingId")
                        .HasColumnType("int");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<int?>("TVShowId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Win")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwardCategoryId");

                    b.HasIndex("AwardId");

                    b.HasIndex("AwardRecipientId");

                    b.HasIndex("CastCrewMemberId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("GenreId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("MovieId");

                    b.HasIndex("MovieSeriesId");

                    b.HasIndex("MovieStudioId");

                    b.HasIndex("ProductionRoleId");

                    b.HasIndex("QuoteId");

                    b.HasIndex("RatingId");

                    b.HasIndex("TVShowId");

                    b.ToTable("AwardRecipient");
                });

            modelBuilder.Entity("MyMDB.Models.CastCrewMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Died")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CastCrewMember");
                });

            modelBuilder.Entity("MyMDB.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("MyMDB.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AirDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("int");

                    b.Property<int>("TVShowId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TVShowId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("MyMDB.Models.Fact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AwardCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("AwardId")
                        .HasColumnType("int");

                    b.Property<int?>("AwardRecipientId")
                        .HasColumnType("int");

                    b.Property<int?>("CastCrewMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int>("FactTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<int?>("JobRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("MediaFileId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieSeriesId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieStudioId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductionRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("int");

                    b.Property<int?>("RatingId")
                        .HasColumnType("int");

                    b.Property<int?>("TVShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwardCategoryId");

                    b.HasIndex("AwardId");

                    b.HasIndex("AwardRecipientId");

                    b.HasIndex("CastCrewMemberId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("FactTypeId");

                    b.HasIndex("GenreId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("MovieId");

                    b.HasIndex("MovieSeriesId");

                    b.HasIndex("MovieStudioId");

                    b.HasIndex("ProductionRoleId");

                    b.HasIndex("QuoteId");

                    b.HasIndex("RatingId");

                    b.HasIndex("TVShowId");

                    b.ToTable("Facts");
                });

            modelBuilder.Entity("MyMDB.Models.FactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FactTypes");
                });

            modelBuilder.Entity("MyMDB.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<int?>("TVShowId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("TVShowId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MyMDB.Models.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobRoles");
                });

            modelBuilder.Entity("MyMDB.Models.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AwardCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("AwardId")
                        .HasColumnType("int");

                    b.Property<int?>("CastCrewMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<int?>("JobRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MediaFileId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieSeriesId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieStudioId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductionRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("QuoteId")
                        .HasColumnType("int");

                    b.Property<int?>("RatingId")
                        .HasColumnType("int");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<int?>("TVShowId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwardCategoryId");

                    b.HasIndex("AwardId");

                    b.HasIndex("CastCrewMemberId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("GenreId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("MovieId");

                    b.HasIndex("MovieSeriesId");

                    b.HasIndex("MovieStudioId");

                    b.HasIndex("ProductionRoleId");

                    b.HasIndex("QuoteId");

                    b.HasIndex("RatingId");

                    b.HasIndex("TVShowId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("BoxOffice")
                        .HasColumnType("float");

                    b.Property<double?>("Budget")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("MovieSeriesId")
                        .HasColumnType("int");

                    b.Property<int>("MovieStudioId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Release")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tagline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieSeriesId");

                    b.HasIndex("MovieStudioId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MyMDB.Models.MovieSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieSeries");
                });

            modelBuilder.Entity("MyMDB.Models.MovieStudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieStudios");
                });

            modelBuilder.Entity("MyMDB.Models.ProductionRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CastCrewMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CreditOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int>("JobRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CastCrewMemberId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("MovieId");

                    b.ToTable("ProductionRoles");
                });

            modelBuilder.Entity("MyMDB.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("MyMDB.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("MovieId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("MyMDB.Models.TVShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("datetime2");

                    b.Property<int>("EpisodeLength")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("TVShows");
                });

            modelBuilder.Entity("AwardRecipientMediaFile", b =>
                {
                    b.HasOne("MyMDB.Models.AwardRecipient", null)
                        .WithMany()
                        .HasForeignKey("AwardRecipientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDB.Models.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMDB.Models.AwardRecipient", b =>
                {
                    b.HasOne("MyMDB.Models.AwardCategory", "AwardCategory")
                        .WithMany("AwardRecipients")
                        .HasForeignKey("AwardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDB.Models.Award", "Award")
                        .WithMany("AwardRecipients")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDB.Models.AwardRecipient", null)
                        .WithMany("AwardRecipients")
                        .HasForeignKey("AwardRecipientId");

                    b.HasOne("MyMDB.Models.CastCrewMember", "CastCrewMember")
                        .WithMany("AwardRecipients")
                        .HasForeignKey("CastCrewMemberId");

                    b.HasOne("MyMDB.Models.Character", null)
                        .WithMany("AwardRecipients")
                        .HasForeignKey("CharacterId");

                    b.HasOne("MyMDB.Models.Episode", "Episode")
                        .WithMany("AwardRecipients")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("MyMDB.Models.Genre", null)
                        .WithMany("AwardRecipients")
                        .HasForeignKey("GenreId");

                    b.HasOne("MyMDB.Models.JobRole", null)
                        .WithMany("AwardRecipients")
                        .HasForeignKey("JobRoleId");

                    b.HasOne("MyMDB.Models.Movie", "Movie")
                        .WithMany("AwardRecipients")
                        .HasForeignKey("MovieId");

                    b.HasOne("MyMDB.Models.MovieSeries", null)
                        .WithMany("AwardRecipients")
                        .HasForeignKey("MovieSeriesId");

                    b.HasOne("MyMDB.Models.MovieStudio", null)
                        .WithMany("AwardRecipients")
                        .HasForeignKey("MovieStudioId");

                    b.HasOne("MyMDB.Models.ProductionRole", null)
                        .WithMany("AwardRecipients")
                        .HasForeignKey("ProductionRoleId");

                    b.HasOne("MyMDB.Models.Quote", null)
                        .WithMany("AwardRecipients")
                        .HasForeignKey("QuoteId");

                    b.HasOne("MyMDB.Models.Rating", null)
                        .WithMany("AwardRecipients")
                        .HasForeignKey("RatingId");

                    b.HasOne("MyMDB.Models.TVShow", "TVShow")
                        .WithMany("AwardRecipients")
                        .HasForeignKey("TVShowId");

                    b.Navigation("Award");

                    b.Navigation("AwardCategory");

                    b.Navigation("CastCrewMember");

                    b.Navigation("Episode");

                    b.Navigation("Movie");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("MyMDB.Models.Episode", b =>
                {
                    b.HasOne("MyMDB.Models.TVShow", "TVShow")
                        .WithMany("Episodes")
                        .HasForeignKey("TVShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("MyMDB.Models.Fact", b =>
                {
                    b.HasOne("MyMDB.Models.AwardCategory", null)
                        .WithMany("Facts")
                        .HasForeignKey("AwardCategoryId");

                    b.HasOne("MyMDB.Models.Award", null)
                        .WithMany("Facts")
                        .HasForeignKey("AwardId");

                    b.HasOne("MyMDB.Models.AwardRecipient", null)
                        .WithMany("Facts")
                        .HasForeignKey("AwardRecipientId");

                    b.HasOne("MyMDB.Models.CastCrewMember", "CastCrewMember")
                        .WithMany("Facts")
                        .HasForeignKey("CastCrewMemberId");

                    b.HasOne("MyMDB.Models.Character", null)
                        .WithMany("Facts")
                        .HasForeignKey("CharacterId");

                    b.HasOne("MyMDB.Models.Episode", "Episode")
                        .WithMany("Facts")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("MyMDB.Models.FactType", "FactType")
                        .WithMany()
                        .HasForeignKey("FactTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDB.Models.Genre", null)
                        .WithMany("Facts")
                        .HasForeignKey("GenreId");

                    b.HasOne("MyMDB.Models.JobRole", null)
                        .WithMany("Facts")
                        .HasForeignKey("JobRoleId");

                    b.HasOne("MyMDB.Models.MediaFile", null)
                        .WithMany("Facts")
                        .HasForeignKey("MediaFileId");

                    b.HasOne("MyMDB.Models.Movie", "Movie")
                        .WithMany("Facts")
                        .HasForeignKey("MovieId");

                    b.HasOne("MyMDB.Models.MovieSeries", null)
                        .WithMany("Facts")
                        .HasForeignKey("MovieSeriesId");

                    b.HasOne("MyMDB.Models.MovieStudio", null)
                        .WithMany("Facts")
                        .HasForeignKey("MovieStudioId");

                    b.HasOne("MyMDB.Models.ProductionRole", null)
                        .WithMany("Facts")
                        .HasForeignKey("ProductionRoleId");

                    b.HasOne("MyMDB.Models.Quote", null)
                        .WithMany("Facts")
                        .HasForeignKey("QuoteId");

                    b.HasOne("MyMDB.Models.Rating", null)
                        .WithMany("Facts")
                        .HasForeignKey("RatingId");

                    b.HasOne("MyMDB.Models.TVShow", "TVShow")
                        .WithMany("Facts")
                        .HasForeignKey("TVShowId");

                    b.Navigation("CastCrewMember");

                    b.Navigation("Episode");

                    b.Navigation("FactType");

                    b.Navigation("Movie");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("MyMDB.Models.Genre", b =>
                {
                    b.HasOne("MyMDB.Models.Movie", null)
                        .WithMany("Genres")
                        .HasForeignKey("MovieId");

                    b.HasOne("MyMDB.Models.TVShow", null)
                        .WithMany("Genres")
                        .HasForeignKey("TVShowId");
                });

            modelBuilder.Entity("MyMDB.Models.MediaFile", b =>
                {
                    b.HasOne("MyMDB.Models.AwardCategory", null)
                        .WithMany("MediaFiles")
                        .HasForeignKey("AwardCategoryId");

                    b.HasOne("MyMDB.Models.Award", "Award")
                        .WithMany("MediaFiles")
                        .HasForeignKey("AwardId");

                    b.HasOne("MyMDB.Models.CastCrewMember", "CastCrewMember")
                        .WithMany("MediaFiles")
                        .HasForeignKey("CastCrewMemberId");

                    b.HasOne("MyMDB.Models.Character", "Character")
                        .WithMany("MediaFiles")
                        .HasForeignKey("CharacterId");

                    b.HasOne("MyMDB.Models.Episode", "Episode")
                        .WithMany("MediaFiles")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("MyMDB.Models.Genre", "Genre")
                        .WithMany("MediaFiles")
                        .HasForeignKey("GenreId");

                    b.HasOne("MyMDB.Models.JobRole", null)
                        .WithMany("MediaFiles")
                        .HasForeignKey("JobRoleId");

                    b.HasOne("MyMDB.Models.MediaFile", null)
                        .WithMany("MediaFiles")
                        .HasForeignKey("MediaFileId");

                    b.HasOne("MyMDB.Models.Movie", "Movie")
                        .WithMany("MediaFiles")
                        .HasForeignKey("MovieId");

                    b.HasOne("MyMDB.Models.MovieSeries", "MovieSeries")
                        .WithMany("MediaFiles")
                        .HasForeignKey("MovieSeriesId");

                    b.HasOne("MyMDB.Models.MovieStudio", "MovieStudio")
                        .WithMany("MediaFiles")
                        .HasForeignKey("MovieStudioId");

                    b.HasOne("MyMDB.Models.ProductionRole", null)
                        .WithMany("MediaFiles")
                        .HasForeignKey("ProductionRoleId");

                    b.HasOne("MyMDB.Models.Quote", null)
                        .WithMany("MediaFiles")
                        .HasForeignKey("QuoteId");

                    b.HasOne("MyMDB.Models.Rating", null)
                        .WithMany("MediaFiles")
                        .HasForeignKey("RatingId");

                    b.HasOne("MyMDB.Models.TVShow", "TVShow")
                        .WithMany("MediaFiles")
                        .HasForeignKey("TVShowId");

                    b.Navigation("Award");

                    b.Navigation("CastCrewMember");

                    b.Navigation("Character");

                    b.Navigation("Episode");

                    b.Navigation("Genre");

                    b.Navigation("Movie");

                    b.Navigation("MovieSeries");

                    b.Navigation("MovieStudio");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("MyMDB.Models.Movie", b =>
                {
                    b.HasOne("MyMDB.Models.MovieSeries", null)
                        .WithMany("Movies")
                        .HasForeignKey("MovieSeriesId");

                    b.HasOne("MyMDB.Models.MovieStudio", "MovieStudio")
                        .WithMany()
                        .HasForeignKey("MovieStudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieStudio");
                });

            modelBuilder.Entity("MyMDB.Models.ProductionRole", b =>
                {
                    b.HasOne("MyMDB.Models.CastCrewMember", "CastCrewMember")
                        .WithMany()
                        .HasForeignKey("CastCrewMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDB.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");

                    b.HasOne("MyMDB.Models.Episode", "Episode")
                        .WithMany("ProductionRoles")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("MyMDB.Models.JobRole", "JobRole")
                        .WithMany()
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMDB.Models.Movie", "Movie")
                        .WithMany("ProductionRoles")
                        .HasForeignKey("MovieId");

                    b.Navigation("CastCrewMember");

                    b.Navigation("Character");

                    b.Navigation("Episode");

                    b.Navigation("JobRole");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyMDB.Models.Quote", b =>
                {
                    b.HasOne("MyMDB.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId");

                    b.HasOne("MyMDB.Models.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId");

                    b.HasOne("MyMDB.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.Navigation("Character");

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyMDB.Models.Rating", b =>
                {
                    b.HasOne("MyMDB.Models.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId");

                    b.HasOne("MyMDB.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId");

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MyMDB.Models.TVShow", b =>
                {
                    b.HasOne("MyMDB.Models.CastCrewMember", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("MyMDB.Models.Award", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.AwardCategory", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.AwardRecipient", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");
                });

            modelBuilder.Entity("MyMDB.Models.CastCrewMember", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.Character", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.Episode", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");

                    b.Navigation("ProductionRoles");
                });

            modelBuilder.Entity("MyMDB.Models.Genre", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.JobRole", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.MediaFile", b =>
                {
                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.Movie", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("Genres");

                    b.Navigation("MediaFiles");

                    b.Navigation("ProductionRoles");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("MyMDB.Models.MovieSeries", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MyMDB.Models.MovieStudio", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.ProductionRole", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.Quote", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.Rating", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Facts");

                    b.Navigation("MediaFiles");
                });

            modelBuilder.Entity("MyMDB.Models.TVShow", b =>
                {
                    b.Navigation("AwardRecipients");

                    b.Navigation("Episodes");

                    b.Navigation("Facts");

                    b.Navigation("Genres");

                    b.Navigation("MediaFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
